name: Bug Report
description: Create a report to help us fix something
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How to trigger the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Upload file '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Upload / File Handling
        - Gallery View
        - Encryption / Decryption
        - User Authentication
        - Folder Management
        - Album Management
        - WebAuthn / Hardware Keys
        - Safes / E2E Encryption
        - Backup / Restore
        - Admin / Settings
        - Other
        
  - type: input
    id: version
    attributes:
      label: Version
      description: App version or git commit
      placeholder: "v1.2.3 or commit hash"
      
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Console logs or screenshots
      render: shell
